///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace module_lib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the module_libRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fb037d8d-e67a-4b06-b757-af19a909f057")]
    public partial class module_libRepository : RepoGenBaseFolder
    {
        static module_libRepository instance = new module_libRepository();

        /// <summary>
        /// Gets the singleton class instance representing the module_libRepository element repository.
        /// </summary>
        [RepositoryFolder("fb037d8d-e67a-4b06-b757-af19a909f057")]
        public static module_libRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public module_libRepository() 
            : base("module_libRepository", "/", null, 0, false, "fb037d8d-e67a-4b06-b757-af19a909f057", ".\\RepositoryImages\\module_libRepositoryfb037d8d.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fb037d8d-e67a-4b06-b757-af19a909f057")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class module_libRepositoryFolders
    {
    }
#pragma warning restore 0436
}
