///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace repositories_
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Repository2 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a6c12276-3362-48f4-8ecd-ccb9264c9c0f")]
    public partial class Repository2 : RepoGenBaseFolder
    {
        static Repository2 instance = new Repository2();

        /// <summary>
        /// Gets the singleton class instance representing the Repository2 element repository.
        /// </summary>
        [RepositoryFolder("a6c12276-3362-48f4-8ecd-ccb9264c9c0f")]
        public static Repository2 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Repository2() 
            : base("Repository2", "/", null, 0, false, "a6c12276-3362-48f4-8ecd-ccb9264c9c0f", ".\\RepositoryImages\\Repository2a6c12276.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a6c12276-3362-48f4-8ecd-ccb9264c9c0f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Repository2Folders
    {
    }
#pragma warning restore 0436
}
