///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the repositoriesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9eadaa62-1922-4ffb-87b9-1fbf08a36773")]
    public partial class repositoriesRepository : RepoGenBaseFolder
    {
        static repositoriesRepository instance = new repositoriesRepository();

        /// <summary>
        /// Gets the singleton class instance representing the repositoriesRepository element repository.
        /// </summary>
        [RepositoryFolder("9eadaa62-1922-4ffb-87b9-1fbf08a36773")]
        public static repositoriesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public repositoriesRepository() 
            : base("repositoriesRepository", "/", null, 0, false, "9eadaa62-1922-4ffb-87b9-1fbf08a36773", ".\\RepositoryImages\\repositoriesRepository9eadaa62.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9eadaa62-1922-4ffb-87b9-1fbf08a36773")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class repositoriesRepositoryFolders
    {
    }
#pragma warning restore 0436
}
