///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace global_functions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the global_functionsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b74bf6b4-3c10-49e2-8881-d7aa05332c21")]
    public partial class global_functionsRepository : RepoGenBaseFolder
    {
        static global_functionsRepository instance = new global_functionsRepository();

        /// <summary>
        /// Gets the singleton class instance representing the global_functionsRepository element repository.
        /// </summary>
        [RepositoryFolder("b74bf6b4-3c10-49e2-8881-d7aa05332c21")]
        public static global_functionsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public global_functionsRepository() 
            : base("global_functionsRepository", "/", null, 0, false, "b74bf6b4-3c10-49e2-8881-d7aa05332c21", ".\\RepositoryImages\\global_functionsRepositoryb74bf6b4.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b74bf6b4-3c10-49e2-8881-d7aa05332c21")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class global_functionsRepositoryFolders
    {
    }
#pragma warning restore 0436
}
