///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace playground
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the playgroundRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ad0f3130-4cce-4bde-bc8e-05bc0c06e04f")]
    public partial class playgroundRepository : RepoGenBaseFolder
    {
        static playgroundRepository instance = new playgroundRepository();
        playgroundRepositoryFolders.Form1AppFolder _form1;

        /// <summary>
        /// Gets the singleton class instance representing the playgroundRepository element repository.
        /// </summary>
        [RepositoryFolder("ad0f3130-4cce-4bde-bc8e-05bc0c06e04f")]
        public static playgroundRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public playgroundRepository() 
            : base("playgroundRepository", "/", null, 0, false, "ad0f3130-4cce-4bde-bc8e-05bc0c06e04f", ".\\RepositoryImages\\playgroundRepositoryad0f3130.rximgres")
        {
            _form1 = new playgroundRepositoryFolders.Form1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ad0f3130-4cce-4bde-bc8e-05bc0c06e04f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("982e7b71-84cd-4756-a9e0-34e7cf491deb")]
        public virtual playgroundRepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class playgroundRepositoryFolders
    {
        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("982e7b71-84cd-4756-a9e0-34e7cf491deb")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pic_box_hello_worldInfo;
            RepoItemInfo _pic_box_masterserviceInfo;
            RepoItemInfo _textboxInfo;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 10000, null, true, "982e7b71-84cd-4756-a9e0-34e7cf491deb", "")
            {
                _pic_box_hello_worldInfo = new RepoItemInfo(this, "pic_box_hello_world", "picture[@controlname='pictureBox1']", "", 10000, null, "7682440f-4255-418c-a20b-5d8cb509524a");
                _pic_box_masterserviceInfo = new RepoItemInfo(this, "pic_box_masterservice", "picture[@controlname='pictureBox2']", "", 10000, null, "4c1a3ecb-5c7b-4aef-9430-a45041e8b8cc");
                _textboxInfo = new RepoItemInfo(this, "textbox", "?/?/text[@accessiblerole='Text']", "", 10000, null, "aa083b98-abde-442c-a5ce-275f221475cd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("982e7b71-84cd-4756-a9e0-34e7cf491deb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("982e7b71-84cd-4756-a9e0-34e7cf491deb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The pic_box_hello_world item.
            /// </summary>
            [RepositoryItem("7682440f-4255-418c-a20b-5d8cb509524a")]
            public virtual Ranorex.Picture pic_box_hello_world
            {
                get
                {
                    return _pic_box_hello_worldInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The pic_box_hello_world item info.
            /// </summary>
            [RepositoryItemInfo("7682440f-4255-418c-a20b-5d8cb509524a")]
            public virtual RepoItemInfo pic_box_hello_worldInfo
            {
                get
                {
                    return _pic_box_hello_worldInfo;
                }
            }

            /// <summary>
            /// The pic_box_masterservice item.
            /// </summary>
            [RepositoryItem("4c1a3ecb-5c7b-4aef-9430-a45041e8b8cc")]
            public virtual Ranorex.Picture pic_box_masterservice
            {
                get
                {
                    return _pic_box_masterserviceInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The pic_box_masterservice item info.
            /// </summary>
            [RepositoryItemInfo("4c1a3ecb-5c7b-4aef-9430-a45041e8b8cc")]
            public virtual RepoItemInfo pic_box_masterserviceInfo
            {
                get
                {
                    return _pic_box_masterserviceInfo;
                }
            }

            /// <summary>
            /// The textbox item.
            /// </summary>
            [RepositoryItem("aa083b98-abde-442c-a5ce-275f221475cd")]
            public virtual Ranorex.Text textbox
            {
                get
                {
                    return _textboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The textbox item info.
            /// </summary>
            [RepositoryItemInfo("aa083b98-abde-442c-a5ce-275f221475cd")]
            public virtual RepoItemInfo textboxInfo
            {
                get
                {
                    return _textboxInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
