///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;



namespace playground
{

	
    public partial class Recording1
    {
    	
    	
    	static string source_path = System.IO.Path.GetDirectoryName(System.Windows.Forms.Application.ExecutablePath);
    	static string ocr_folder = Path.Combine(source_path, @"ocr\");
        static	string ocr_reader_zip = "netcoreapp3.0.zip";
        static string ocr_reader_exe = @"netcoreapp3.0\Tesseract.ConsoleDemo.exe";
        static	string ocr_target_app = "target_app_for_ocr_test.exe";
    	
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
  		private void Init(){

      


		}
  
   		

        public void start_ocr()
        {
            Ranorex.Report.Info("exec dir: " + source_path);
            if(Directory.Exists(ocr_folder)){
            	Directory.Delete(Path.Combine(source_path, @"ocr\netcoreapp3.0"), true);
            }

        	System.IO.Compression.ZipFile.ExtractToDirectory(Path.Combine(ocr_folder, ocr_reader_zip), ocr_folder);
        	
		  	//string pictureBox1 = repo.Form1.pic_box_hello_world;
		  	Ranorex.Unknown pictureBox1  = repo.Form1.pic_box_hello_worldInfo.CreateAdapter<Ranorex.Unknown>(true);
		  	Ranorex.Unknown pictureBox2  = repo.Form1.pic_box_masterserviceInfo.CreateAdapter<Ranorex.Unknown>(true);
		  	Ranorex.Unknown textbox  = repo.Form1.textboxInfo.CreateAdapter<Ranorex.Unknown>(true);		  	

		  	SaveScreenshot(textbox);
		  	get_string_from_ocr();
        }
        
        
        public static void SaveScreenshot(Ranorex.Unknown element)
	    {
   			Bitmap image = Ranorex.Imaging.CaptureDesktopImage(element);
   			String pathImageName = Path.Combine(ocr_folder, @"myimage.png");
   			image.Save(pathImageName, System.Drawing.Imaging.ImageFormat.Png);
	    }
   		
   		public static string get_string_from_ocr(){
   			ProcessStartInfo startInfo = new ProcessStartInfo();				
   			startInfo.FileName = Path.Combine(ocr_folder, ocr_reader_exe);
   			startInfo.WorkingDirectory  = Path.Combine( ocr_folder ,@"netcoreapp3.0");
			startInfo.Arguments = Path.Combine(ocr_folder, "myimage.png");
			startInfo.UseShellExecute = false;
			startInfo.RedirectStandardOutput = true;
			startInfo.CreateNoWindow = true;
			
			Process process;
			process = Process.Start(startInfo);
			process.WaitForExit();
			var result = process.StandardOutput.ReadToEnd();
			Ranorex.Report.Info(result.ToString());
			return result;
   		}
        
        public void start_SUT(){
        	ProcessStartInfo startInfo = new ProcessStartInfo();				
   			startInfo.FileName = Path.Combine(ocr_folder, ocr_target_app);
   			Process process;
			process = Process.Start(startInfo);
			

        }
        
        public void stop_SUT(){
        	foreach (var process in Process.GetProcessesByName("target_app_for_ocr_test"))
			{
			    process.Kill();
			}
        }

    }
}


/*
 * 
 * 
 * 	Bitmap bmp = Ranorex.Imaging.CaptureDesktopImage(pictureBox1);
	CompressedImage image = new CompressedImage(bmp, ImageFormat.Png);
	image.Store(@"d:\projects\ocr_pics\myimage.png");
*/